"""
Run once to set up environment.
"""
from collections import OrderedDict

parameters = OrderedDict({
    "global": {
        "MissionName": {"value": "testbed", "comment": "directory name for data produced in path generation"},
        "MissionFile": {"value": "testbed.csv", "comment": "A full path to the sensing mission requirements"},
        "NumberOfDrones": {"value": 4, "comment": "Number of drone operating in the file system"}
    },

    "path_generation": {
        "NumberOfPlans": {"value": 8,
                          "comment": "Number of plans generated by each drone in the system (only 1 selected)"},
        "PathMode": {"value": "normal", "comment": "two modes: normal for visiting all possible cells, "
                                                   "and greedy for visiting just one cell"}
        # "MaximumNumberOfVisitedCells": {"value": 6,
        #                                 "comment": "Number of cells visited by each drone (NEEDS TO BE REMOVED)"}
    },

    "epos": {
        "EPOSstdout": {"value": False, "comment": "Show the stdout from EPOS"},
        "EPOSstderr": {"value": False, "comment": "Show the stderr from EPOS"},
        "NumberOfSimulations": {"value": 1, "comment": "The number of runs done by EPOS"},
        "IterationsPerSimulation": 32,
        "NumberOfChildren": 2,
        "PlanDimension": 6,
        "Shuffle": 0,
        "ShuffleFile": "permuation.csv",
        "NumberOfWeights": 2,
        "WeightsString": "0.0,0.0",
        "behaviours": "same",
        "agentsBehaviourPath": "default",
        "constraint": "SOFT",
        "constraintPlansPath": "default",
        "constraintCostsPath": "default",
        "strategy": "never",
        "periodically.reorganizationPeriod": 3,
        "convergence.memorizationOffset": 5,
        "globalCost.reductionThreshold": 0.5,
        "strategy.reorganizationSeed": 0,
        "globalCostFunction": {"value": "MIS",
                               "comment": "For drone sensing missions, this should be MIS (Sensing MISmatch).  "
                                          "It should be noted that this is a custom function"},
        "scaling": "STD",
        "localCostFunction": "INDEX",
        "logger.GlobalCostLogger": "true",
        "logger.LocalCostMultiObjectiveLogger": "true",
        "logger.TerminationLogger": "true",
        "logger.SelectedPlanLogger": "true",
        "logger.GlobalResponseVectorLogger": "true",
        "logger.PlanFrequencyLogger": "true",
        "logger.UnfairnessLogger": "true",
        "logger.GlobalComplexCostLogger": "false",
        "logger.WeightsLogger": "false",
        "logger.ReorganizationLogger": "true",
        "logger.VisualizerLogger": "false",
        "logger.PositionLogger": "true",
        "logger.HardConstraintLogger": "false"
    },

    "drone": {
        "BatteryCapacity": 2700,
        "BodyMass": 0.027,
        "BatteryMass": 0.005,
        "NumberOfRotors": 4,
        "RotorDiameter": 0.03,
        "ProjectedBodyArea": 0.0599,
        "ProjectedBatteryArea": 0.0037,
        "PowerEfficiency": 1.25,
        "GroundSpeed": 6.94,
        "AirSpeed": 8.5
    },

    "environment": {
        "AirDensity": 1.225
    }
})

with open("drone_sense.properties", "w") as file:
    for section, section_params in parameters.items():
        file.write(f"[{section}]\n")
        for key, item in section_params.items():
            if type(item) is dict:
                if "comment" in item:
                    file.write(f"# {item['comment']}\n")
                if "value" in item:
                    file.write(f"{key}={item['value']}\n")
            else:
                file.write(f"{key}={item}\n")
        file.write("\n")
